micronaut:
  application:
    name: kool-queue-app-test
  scheduler:
    kool-queue:
      max-concurrent-tasks: 4
      shutdown-timeout-seconds: 30
      enable-management-endpoints: true

endpoints:
  all:
    enabled: true
    sensitive: false
  health:
    enabled: true
  kool-queue-scheduler:
    enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 'changeme'
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
        - com.freesoullabs.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
