micronaut:
  application:
    name: kool-queue-app-test
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 'changeme'
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
        - com.freesoullabs.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
